spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cosmo_cats}
    username: ${DB_USERNAME:cosmo}
    password: ${DB_PASSWORD:cosmo}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    org.springframework: INFO
    
feature-toggle:
  toggles:
    cosmo-cats: true
    kitty-products: false

security:
  api-key-header: X-API-KEY
  api-key: cosmo-cats-api-key
  jwt:
    secret: cosmo-cats-jwt-secret
    jws-algorithm: HS256
    roles-claim: roles
